services:
  - type: web
  - name: java
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        fromDatabase:
          name: mongo
          port: 27017
          protocol: tcp
    buildCommand: |
      docker build -t java-app .
    startCommand: java -jar app.jar
    healthCheckPath: /actuator/health
    internalPorts:
      - 8080
    instanceCount: 1
    plan: starter

databases:
  - name: mongo
    plan: starter

builds:
  - name: java
    dockerfilePath: Dockerfile
    context: .